#!/bin/bash

# Manual Testing Guide - Delete Validation Fix
# Run these tests manually in browser after deployment

echo "🧪 Delete Validation Testing Guide"
echo "=================================="
echo ""
echo "Prerequisites:"
echo "✅ Application running (docker-compose up -d)"
echo "✅ Backend API accessible"
echo "✅ Login to application with valid credentials"
echo ""

# Test Data Setup
echo "📝 Test Data Setup"
echo "------------------"
echo ""
echo "1. CREATE TEST OFFICE (Kantor Test)"
echo "   - Name: 'Test Office DELETE'"
echo "   - Location: 'Test Location'"
echo "   - Copy the ID (e.g., 999)"
echo ""
echo "2. CREATE TEST JOB POSITION (Jabatan Test)"
echo "   - Name: 'Test Position DELETE'"
echo "   - Copy the ID (e.g., 888)"
echo ""
echo "3. CREATE TEST EMPLOYEE - Scenario A (Without dependencies)"
echo "   - Name: 'Employee Test A'"
echo "   - Office: Any existing office"
echo "   - Position: Any existing position"
echo "   - NO photo"
echo ""
echo "4. CREATE TEST EMPLOYEE - Scenario B (With photo)"
echo "   - Name: 'Employee Test B'"
echo "   - Office: Any existing office"
echo "   - Position: Any existing position"
echo "   - UPLOAD photo"
echo ""
echo "5. CREATE TEST EMPLOYEE - Scenario C (Uses Test Office/Position)"
echo "   - Name: 'Employee Test C'"
echo "   - Office: 'Test Office DELETE' (from step 1)"
echo "   - Position: 'Test Position DELETE' (from step 2)"
echo ""

# Test Cases
echo ""
echo "🎯 Test Case 1: Delete Employee WITHOUT Photo"
echo "---------------------------------------------"
echo "Steps:"
echo "  1. Go to Karyawan list page"
echo "  2. Find 'Employee Test A'"
echo "  3. Click Delete button"
echo "  4. Confirm deletion"
echo ""
echo "Expected Result:"
echo "  ✅ Success toast: 'Employee deleted successfully'"
echo "  ✅ Employee removed from list"
echo "  ✅ No errors in console"
echo ""
echo "To verify: Refresh page → 'Employee Test A' should be gone"
echo ""
echo "---"
echo ""

echo "🎯 Test Case 2: Delete Employee WITH Photo"
echo "------------------------------------------"
echo "Steps:"
echo "  1. Go to Karyawan detail page for 'Employee Test B'"
echo "  2. Verify photo is displayed"
echo "  3. Click main Delete button (delete employee)"
echo "  4. Confirm deletion"
echo ""
echo "Expected Result:"
echo "  ✅ Success toast: 'Employee deleted successfully'"
echo "  ✅ Redirect to employee list"
echo "  ✅ Employee removed from database"
echo ""
echo "To verify: Search for 'Employee Test B' → should return no results"
echo ""
echo "---"
echo ""

echo "🎯 Test Case 3: Delete Employee Photo Only"
echo "------------------------------------------"
echo "Steps:"
echo "  1. Create new employee with photo OR use existing"
echo "  2. Go to employee detail page"
echo "  3. Click 'Delete Photo' button"
echo "  4. Confirm deletion"
echo ""
echo "Expected Result:"
echo "  ✅ Success toast: 'Photo deleted successfully'"
echo "  ✅ Photo removed from UI (shows placeholder)"
echo "  ✅ Employee still exists"
echo "  ✅ Page does NOT redirect"
echo ""
echo "To verify: Refresh page → employee exists but no photo"
echo ""
echo "---"
echo ""

echo "🎯 Test Case 4: Delete Office WITH Employees (Should FAIL)"
echo "----------------------------------------------------------"
echo "Steps:"
echo "  1. Go to Kantor detail page for 'Test Office DELETE'"
echo "  2. Verify 'Employee Test C' is assigned to this office"
echo "  3. Click Delete button"
echo "  4. Confirm deletion"
echo ""
echo "Expected Result:"
echo "  ❌ Error toast showing backend message"
echo "  ❌ Office NOT deleted"
echo "  ❌ Page does NOT redirect"
echo "  ❌ Office still appears in list"
echo ""
echo "Possible error messages:"
echo "  - 'Failed to delete office'"
echo "  - 'Cannot delete office: has associated employees'"
echo "  - Or similar backend error message"
echo ""
echo "To verify: Refresh → office still exists"
echo ""
echo "---"
echo ""

echo "🎯 Test Case 5: Delete Office WITHOUT Employees (Should SUCCEED)"
echo "----------------------------------------------------------------"
echo "Steps:"
echo "  1. First, delete 'Employee Test C' (to free up the office)"
echo "  2. Go to Kantor detail page for 'Test Office DELETE'"
echo "  3. Click Delete button"
echo "  4. Confirm deletion"
echo ""
echo "Expected Result:"
echo "  ✅ Success toast: 'Office deleted successfully'"
echo "  ✅ Redirect to office list"
echo "  ✅ Office removed from list"
echo ""
echo "To verify: Search for 'Test Office DELETE' → no results"
echo ""
echo "---"
echo ""

echo "🎯 Test Case 6: Delete Job Position WITH Employees (Should FAIL)"
echo "----------------------------------------------------------------"
echo "Steps:"
echo "  1. Create new employee with 'Test Position DELETE'"
echo "  2. Go to Jabatan detail page for 'Test Position DELETE'"
echo "  3. Click Delete button"
echo "  4. Confirm deletion"
echo ""
echo "Expected Result:"
echo "  ❌ Error toast showing backend message"
echo "  ❌ Position NOT deleted"
echo "  ❌ Page does NOT redirect"
echo "  ❌ Position still appears in list"
echo ""
echo "Possible error messages:"
echo "  - 'Failed to delete job position'"
echo "  - 'Cannot delete position: assigned to employees'"
echo "  - Or similar backend error message"
echo ""
echo "To verify: Refresh → position still exists"
echo ""
echo "---"
echo ""

echo "🎯 Test Case 7: Delete Job Position WITHOUT Employees (Should SUCCEED)"
echo "----------------------------------------------------------------------"
echo "Steps:"
echo "  1. First, delete all employees with 'Test Position DELETE'"
echo "  2. Go to Jabatan detail page for 'Test Position DELETE'"
echo "  3. Click Delete button"
echo "  4. Confirm deletion"
echo ""
echo "Expected Result:"
echo "  ✅ Success toast: 'Job position deleted successfully'"
echo "  ✅ Redirect to position list"
echo "  ✅ Position removed from list"
echo ""
echo "To verify: Search for 'Test Position DELETE' → no results"
echo ""
echo "---"
echo ""

echo "🎯 Test Case 8: Delete from List Page"
echo "-------------------------------------"
echo "Steps:"
echo "  1. Go to Karyawan list page"
echo "  2. Click delete on any employee row"
echo "  3. Confirm deletion"
echo ""
echo "Expected Result:"
echo "  ✅ Success toast: 'Employee deleted successfully'"
echo "  ✅ List auto-refreshes"
echo "  ✅ Employee removed from list"
echo "  ✅ Stay on same page (no redirect)"
echo ""
echo "Same test for:"
echo "  - Kantor list page"
echo "  - Jabatan list page"
echo ""
echo "---"
echo ""

# Error Scenarios
echo "❌ Error Scenarios to Test"
echo "==========================="
echo ""
echo "1. Network Error Simulation:"
echo "   - Stop backend (docker-compose down on backend)"
echo "   - Try to delete any item"
echo "   Expected: Error toast with connection error message"
echo ""
echo "2. Invalid ID:"
echo "   - Manually navigate to /dashboard/karyawan/99999"
echo "   - Click delete"
echo "   Expected: 404 error or 'Not found' message"
echo ""
echo "3. Permission Error (if implemented):"
echo "   - Login with limited user"
echo "   - Try to delete protected resource"
echo "   Expected: 403 error or 'Permission denied' message"
echo ""

# Browser Console Checks
echo ""
echo "🔍 Browser Console Checks"
echo "========================="
echo ""
echo "For EACH test, check browser console (F12):"
echo ""
echo "✅ No red errors should appear"
echo "✅ API calls should show proper response:"
echo "   - DELETE /api/karyawan/123"
echo "   - Response: {success: true, message: '...'}"
echo ""
echo "❌ For failed deletes:"
echo "   - Response: {success: false, message: '...'}"
echo "   - Should show informative error in console"
echo ""

# Network Tab Inspection
echo ""
echo "🌐 Network Tab Inspection"
echo "========================="
echo ""
echo "Check Network tab for delete operations:"
echo ""
echo "1. Request Headers:"
echo "   ✅ X-XSRF-TOKEN: <token>"
echo "   ✅ X-CSRF-TOKEN: <token>"
echo "   ✅ Content-Type: application/json"
echo ""
echo "2. Response Status:"
echo "   ✅ Success: 200 OK"
echo "   ❌ Error: 409 Conflict (foreign key)"
echo "   ❌ Error: 404 Not Found"
echo "   ❌ Error: 500 Internal Server Error"
echo ""
echo "3. Response Body:"
echo "   Should contain 'success' and 'message' fields"
echo ""

# Success Criteria
echo ""
echo "✅ Overall Success Criteria"
echo "==========================="
echo ""
echo "All tests PASS if:"
echo "  ✅ Delete succeeds when it should"
echo "  ❌ Delete fails gracefully when it should"
echo "  ✅ Success messages appear for successful deletes"
echo "  ❌ Error messages appear for failed deletes"
echo "  ✅ No false positive success messages"
echo "  ✅ UI updates correctly (refresh, redirect)"
echo "  ✅ No console errors"
echo "  ✅ Consistent behavior across all delete operations"
echo ""

# Known Issues
echo ""
echo "⚠️  Known Issues to Watch For"
echo "=============================="
echo ""
echo "1. Backend not returning 'success' field"
echo "   → Fix: Update backend API to include success boolean"
echo ""
echo "2. CSRF token missing"
echo "   → Fix: Ensure backend sets CSRF cookie"
echo ""
echo "3. Photo delete not working"
echo "   → Fix: Check DELETE /api/karyawan/:id/photo endpoint"
echo ""
echo "4. Foreign key constraint not enforced"
echo "   → Fix: Database should have proper foreign keys"
echo ""

# Reporting
echo ""
echo "📊 Test Results Template"
echo "========================"
echo ""
echo "Copy this and fill in results:"
echo ""
echo "Test Date: $(date)"
echo "Tester: _____________"
echo "Environment: _____________"
echo ""
echo "| Test Case | Status | Notes |"
echo "|-----------|--------|-------|"
echo "| TC1: Delete Employee No Photo | [ ] PASS [ ] FAIL | |"
echo "| TC2: Delete Employee With Photo | [ ] PASS [ ] FAIL | |"
echo "| TC3: Delete Photo Only | [ ] PASS [ ] FAIL | |"
echo "| TC4: Delete Office (Should Fail) | [ ] PASS [ ] FAIL | |"
echo "| TC5: Delete Office (Should Succeed) | [ ] PASS [ ] FAIL | |"
echo "| TC6: Delete Position (Should Fail) | [ ] PASS [ ] FAIL | |"
echo "| TC7: Delete Position (Should Succeed) | [ ] PASS [ ] FAIL | |"
echo "| TC8: Delete from List Page | [ ] PASS [ ] FAIL | |"
echo ""
echo "Issues Found:"
echo "1. _____________________________________________"
echo "2. _____________________________________________"
echo "3. _____________________________________________"
echo ""
echo "Overall Status: [ ] ALL PASS [ ] NEEDS FIX"
echo ""

echo ""
echo "✅ Testing guide complete!"
echo ""
echo "To run manual tests, follow each test case in your browser."
echo "Use browser DevTools (F12) to monitor network and console."
echo ""
